version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./data:/app/data
    env_file:
      - .env
